apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: wk2todymt-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/wk2todymt-java-quarkus-gitops